# Generated by Django 4.1.3 on 2022-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_content_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
